# Set a plain language title for the site.
title: HCD Work Request

# Write a short description for the site. This is used for "meta description."
description: Internal form for requesting ad-hoc design work from Bixal HCD team

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Enable for live hosting on GitHub Pages
baseurl: /hcd-work-request

# Remove generation of additional style.css
theme: null

collections:
  slides:
    output: true
